name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
            compose-file: ./docker-compose.yaml
            up-flags: -d

      - name: Run test to check empty array test
        run: npx playwright test tests/empty-array.test.ts

      - name: Run test to check remaining tests without empty array
        run: npx playwright test tests/user-controller.test.ts
